/*
 * NFL v3 Odds
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bettrnation.model.nfl.odds;

import com.google.gson.annotations.SerializedName;

public record BettingEntityMetadata(
    @SerializedName("RecordId") Integer recordId, @SerializedName("Name") String name) {}
