package com.bettrnation.model.nfl;

import com.google.gson.annotations.SerializedName;
import java.math.BigDecimal;
import java.util.List;

public record AdvancedPlayer(
    @SerializedName("PlayerID") Integer playerID,
    @SerializedName("Name") String name,
    @SerializedName("TeamID") Integer teamID,
    @SerializedName("Team") String team,
    @SerializedName("Position") String position,
    @SerializedName("FantasyPosition") String fantasyPosition,
    @SerializedName("PositionGroup") String positionGroup,
    @SerializedName("BMI") BigDecimal BMI,
    @SerializedName("BMIRank") Integer bmIRank,
    @SerializedName("HandSize") BigDecimal handSize,
    @SerializedName("HandSizeRank") Integer handSizeRank,
    @SerializedName("ArmLength") BigDecimal armLength,
    @SerializedName("ArmLengthRank") Integer armLengthRank,
    @SerializedName("QualityScore") BigDecimal qualityScore,
    @SerializedName("QualityScoreRank") Integer qualityScoreRank,
    @SerializedName("FortyYardDash") BigDecimal fortyYardDash,
    @SerializedName("FortyYardDashRank") Integer fortyYardDashRank,
    @SerializedName("ThreeConeDrill") BigDecimal threeConeDrill,
    @SerializedName("ThreeConeDrillRank") Integer threeConeDrillRank,
    @SerializedName("TwentyYardShuttle") BigDecimal twentyYardShuttle,
    @SerializedName("TwentyYardShuttleRank") Integer twentyYardShuttleRank,
    @SerializedName("AgilityScore") BigDecimal agilityScore,
    @SerializedName("AgilityScoreRank") Integer agilityScoreRank,
    @SerializedName("VerticalJump") BigDecimal verticalJump,
    @SerializedName("VerticalJumpRank") Integer verticalJumpRank,
    @SerializedName("BroadJump") BigDecimal broadJump,
    @SerializedName("BroadJumpRank") Integer broadJumpRank,
    @SerializedName("BurstScore") BigDecimal burstScore,
    @SerializedName("BurstScoreRank") Integer burstScoreRank,
    @SerializedName("SPARQx") BigDecimal spARQx,
    @SerializedName("SPARQxRank") Integer spARQxRank,
    @SerializedName("AthleticismScore") BigDecimal athleticismScore,
    @SerializedName("AthleticismScoreRank") Integer athleticismScoreRank,
    @SerializedName("SpeedScore") BigDecimal speedScore,
    @SerializedName("SpeedScoreRank") Integer speedScoreRank,
    @SerializedName("ThrowVelocity") BigDecimal throwVelocity,
    @SerializedName("ThrowVelocityRank") Integer throwVelocityRank,
    @SerializedName("WonderlicScore") BigDecimal wonderlicScore,
    @SerializedName("WonderlicScoreRank") Integer wonderlicScoreRank,
    @SerializedName("HeightAdjustedSpeedScore") BigDecimal heightAdjustedSpeedScore,
    @SerializedName("HeightAdjustedSpeedScoreRank") Integer heightAdjustedSpeedScoreRank,
    @SerializedName("CatchRadius") BigDecimal catchRadius,
    @SerializedName("CatchRadiusRank") Integer catchRadiusRank,
    @SerializedName("BenchPress") BigDecimal benchPress,
    @SerializedName("BenchPressRank") Integer benchPressRank,
    @SerializedName("PlaymakingRadius") BigDecimal playmakingRadius,
    @SerializedName("PlaymakingRadiusRank") Integer playmakingRadiusRank,
    @SerializedName("HighlightClip") String highlightClip,
    @SerializedName("MedicalHistory") List<AdvancedPlayerMedical> medicalHistory,
    @SerializedName("ComparablePlayers") List<PlayerInfo> comparablePlayers,
    @SerializedName("AdvancedPlayerSeasons") List<AdvancedPlayerSeason> advancedPlayerSeasons,
    @SerializedName("AdvancedPlayerGames") List<AdvancedPlayerGame> advancedPlayerGames) {}
