package com.bettrnation.model.nfl;

import com.google.gson.annotations.SerializedName;
import java.math.BigDecimal;

public record Team(
    @SerializedName("Key") String key,
    @SerializedName("TeamID") Integer teamID,
    @SerializedName("PlayerID") Integer playerID,
    @SerializedName("City") String city,
    @SerializedName("Name") String name,
    @SerializedName("Conference") String conference,
    @SerializedName("Division") String division,
    @SerializedName("FullName") String fullName,
    @SerializedName("StadiumID") Integer stadiumID,
    @SerializedName("ByeWeek") Integer byeWeek,
    @SerializedName("AverageDraftPosition") BigDecimal averageDraftPosition,
    @SerializedName("AverageDraftPositionPPR") BigDecimal averageDraftPositionPPR,
    @SerializedName("HeadCoach") String headCoach,
    @SerializedName("OffensiveCoordinator") String offensiveCoordinator,
    @SerializedName("DefensiveCoordinator") String defensiveCoordinator,
    @SerializedName("SpecialTeamsCoach") String specialTeamsCoach,
    @SerializedName("OffensiveScheme") String offensiveScheme,
    @SerializedName("DefensiveScheme") String defensiveScheme,
    @SerializedName("UpcomingSalary") Integer upcomingSalary,
    @SerializedName("UpcomingOpponent") String upcomingOpponent,
    @SerializedName("UpcomingOpponentRank") Integer upcomingOpponentRank,
    @SerializedName("UpcomingOpponentPositionRank") Integer upcomingOpponentPositionRank,
    @SerializedName("UpcomingFanDuelSalary") Integer upcomingFanDuelSalary,
    @SerializedName("UpcomingDraftKingsSalary") Integer upcomingDraftKingsSalary,
    @SerializedName("UpcomingYahooSalary") Integer upcomingYahooSalary,
    @SerializedName("PrimaryColor") String primaryColor,
    @SerializedName("SecondaryColor") String secondaryColor,
    @SerializedName("TertiaryColor") String tertiaryColor,
    @SerializedName("QuaternaryColor") String quaternaryColor,
    @SerializedName("WikipediaLogoUrl") String wikipediaLogoUrl,
    @SerializedName("WikipediaWordMarkUrl") String wikipediaWordMarkUrl,
    @SerializedName("GlobalTeamID") Integer globalTeamID,
    @SerializedName("DraftKingsName") String draftKingsName,
    @SerializedName("DraftKingsPlayerID") Integer draftKingsPlayerID,
    @SerializedName("FanDuelName") String fanDuelName,
    @SerializedName("FanDuelPlayerID") Integer fanDuelPlayerID,
    @SerializedName("FantasyDraftName") String fantasyDraftName,
    @SerializedName("FantasyDraftPlayerID") Integer fantasyDraftPlayerID,
    @SerializedName("YahooName") String yahooName,
    @SerializedName("YahooPlayerID") Integer yahooPlayerID,
    @SerializedName("StadiumDetails") Stadium stadiumDetails,
    @SerializedName("AverageDraftPosition2QB") BigDecimal averageDraftPosition2QB,
    @SerializedName("AverageDraftPositionDynasty") BigDecimal averageDraftPositionDynasty) {}
