package com.bettrnation.model;

import java.time.LocalDate;

public record Schedule(
    String gameKey,
    Integer seasonType,
    Integer season,
    Integer week,
    LocalDate date,
    String awayTeam,
    String homeTeam,
    String channel,
    Double pointSpread,
    Double overUnder,
    Integer stadiumID,
    Boolean canceled,
    Double geoLat,
    Double geoLong,
    Integer forecastTempLow,
    Integer forecastTempHigh,
    String forecastDescription,
    Integer forecastWindChill,
    Integer forecastWindSpeed,
    Integer awayTeamMoneyLine,
    Integer homeTeamMoneyLine,
    LocalDate day,
    LocalDate dateTime,
    Integer globalGameID,
    Integer globalAwayTeamID,
    Integer globalHomeTeamID,
    Integer scoreID,
    Stadium stadiumDetails,
    String status,
    Boolean isClosed) {}
