package com.bettrnation.model;

public record Standing(
    Integer seasonType,
    Integer season,
    String conference,
    String division,
    String team,
    String name,
    Integer wins,
    Integer losses,
    Integer ties,
    Double percentage,
    Integer pointsFor,
    Integer pointsAgainst,
    Integer netPoints,
    Integer touchdowns,
    Integer divisionWins,
    Integer divisionLosses,
    Integer conferenceWins,
    Integer conferenceLosses,
    Integer teamID,
    Integer divisionTies,
    Integer conferenceTies,
    Integer globalTeamID,
    Integer divisionRank,
    Integer conferenceRank) {}
