package com.bettrnation.model;

public record TeamBasic(
    String key,
    Integer teamID,
    Integer playerID,
    String city,
    String name,
    String conference,
    String division,
    String fullName,
    Integer stadiumID,
    Integer byeWeek,
    Integer globalTeamID,
    String headCoach,
    String primaryColor,
    String secondaryColor,
    String tertiaryColor,
    String quaternaryColor,
    String wikipediaLogoURL,
    String wikipediaWordMarkURL,
    String offensiveCoordinator,
    String defensiveCoordinator,
    String specialTeamsCoach,
    String offensiveScheme,
    String defensiveScheme) {}
